### ISSUE TITLE
Question: implementing the split operation without rebalancing

### ISSUE THREAD

**Issue by bredelings** [ouaffm/outils#2]
Hi, 

I am trying to implement some of the same algorithms (specifically HDT-0) in a different language.

I see that you implement `make_first( )` as a `split( )` followed by an `append( )`, which makes sense.  However, the split( ) is implemented as
* inserting a dummy node at the split point
* rotating the dummy node to the root
and if any rebalancing is being done, then I am not seeing it.

Would you possibly have a reference that describes this method of performing split( ) or either red-black trees or aa-trees, and why it is OK to skip rebalancing?

I see that there is a paper by Tarjan in splitting red-black trees, but it seems to use a different method.

-BenRI

**Comment by bredelings** [comment]
The relevant code is here: https://github.com/ouaffm/outils/blob/master/src/tree/bst/aaforest.rs#L905

**Comment by ouaffm** [comment]
Hi,

it took a little while to get my head around this stuff again. First off, the implementation of the forest follows the C++ implementation described in this paper: [https://refubium.fu-berlin.de/handle/fub188/18151?show=full](url), but using the AA tree balancing mechanism (whereas in the paper, it seems to be vanilla red/black).

Then, with regard to rebalancing: It takes place when isolate() (see line 366 of the module) is called on the dummy node. This function does the heavy lifting, among others applying the function fix_node_balance() on all nodes from the "heir" of the removed node up to the respective (left or right) root.

It might be possible to do this within calls to a specialized rotate() as well. I don't remember why I didn't do this. Most likely I sacrificed a little performance by looping up to the roots again in order not let the code get too messy.

I hope that this will help you. Glad that there are actually some people out there who are interested in this stuff :-)

Kind regards,
Oliver
